feat: allow configuring the name/path of ffprobe
theduke/ffprobe-rs pull request #22
Opened 2023-11-22 13:04 UTC by lovesegfault

Fixes: #21

2023-11-23 10:55 UTC, theduke requested changes
Thanks!

Just one small change.

2023-11-23 10:55 UTC, theduke commented on src/lib.rs
> +    ffprobe_bin: String,
Let's make this a `std::path::PathBuf` instead.

2023-11-23 16:32 UTC, lovesegfault commented on src/lib.rs
> +    ffprobe_bin: String,
I thought about that, but the thing is a bin name (e.g. `ffprobe-custom`) which should be found via `$PATH` isn't really a `PathBuf`, semantically. You can flip this argument, and say that an explicit path (e.g. `/opt/bin/my-ffprobe`) isn't really a `String`, I guess.

I think the best answer might be storing a `PathBuf` but make the builder method take `impl AsRef<Path>` so you can still pass `"bin-name"`.

2023-11-23 16:38 UTC, lovesegfault commented on src/lib.rs
> +    ffprobe_bin: String,
Done :)

2023-11-24 14:09 UTC, theduke commented on src/lib.rs
> +    ffprobe_bin: String,
Yeah, I guess if we are pedantic an `OsString` would be the most generic way to go, but I think PathBuf is fine.

2023-11-24 14:10 UTC, theduke approved these changes

2023-11-24 14:10 UTC, merged