Breaking: convert FfProbeError to enum
theduke/ffprobe-rs pull request #8
Opened 2021-07-27 14:44 UTC by MCOfficer

As per #6 

I have a few more optional things in mind, let me know if you'd like to have them or not:

- Tests - A bit tricky since we basically need to mock system calls, but i can look into it.
- Improve Error formatting - atm we mostly delegate to the wrapped errors.
- Provide stdout as part of the Deserialize error - would be useful for creating bug reports (and for my fuzzing).

2021-07-27 15:26 UTC, egfx-notifications commented
I'd rather not convert the FfProbeError itself into an enum, but add ErrorKind as an enum describing the error. [This is how it's done for `std::io::Error`](https://doc.rust-lang.org/stable/std/io/struct.Error.html#method.kind) and I have also seen this pattern in other projects.

Here's a small snippet from a recent project of mine which does the same in a very rudimentary way:  
```
#[derive(Clone, Debug)]
pub struct MatroxConverterError {
    message: String,
    kind: MatroxConverterErrorKind,
}

#[derive(Clone, Debug, PartialEq)]
pub enum MatroxConverterErrorKind {
    SkippedExisting,
    VirtualDubError(Box<ffprobe::FfProbe>),
}

impl MatroxConverterError {
    fn new(message: impl Into<String>, kind: MatroxConverterErrorKind) -> Self {
        Self {
            message: message.into(),
            kind,
        }
    }

    fn kind(&self) -> MatroxConverterErrorKind {
        self.kind.clone()
    }
}

impl std::fmt::Display for MatroxConverterError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl std::error::Error for MatroxConverterError {}
```

You can then match on `FfprobeError.kind()` while keeping FfprobeError itself as struct.

2021-07-27 15:30 UTC, MCOfficer commented
> 
> 
> I'd rather not convert the FfProbeError itself into an enum, but add ErrorKind as an enum describing the error. [This is how it's done for `std::io::Error`](https://doc.rust-lang.org/stable/std/io/struct.Error.html#method.kind) and I have also seen this pattern in other projects.

Interesting. I've derived this among others from [thiserror](https://lib.rs/crates/thiserror). I wonder if there are compelling reasons to prefer one over the other. Will research later.

2021-07-28 09:31 UTC, MCOfficer commented
Rudimentary research has been done, and the answer is - both is fine?

There are several examples à la std::io::Error:
- [serde_json](https://docs.rs/serde_json/1.0.64/serde_json/struct.Error.html)
- [isahc](https://docs.rs/isahc/1.4.0/isahc/error/struct.Error.html)
- [clap](https://docs.rs/clap/2.33.3/clap/struct.Error.html)
- [aho_corasick](https://docs.rs/aho-corasick/0.7.18/aho_corasick/struct.Error.html)

On the other hand, enums seem to be common as well.
- [thiserror](https://lib.rs/crates/thiserror), as mentioned above
- [Burntsushi's blog post on error handling](https://blog.burntsushi.net/rust-error-handling/#composing-custom-error-types)
- [sled](https://docs.rs/sled/0.34.6/sled/enum.Error.html)
- [regex](https://docs.rs/regex/1.5.4/regex/enum.Error.html)
- [base64](https://docs.rs/base64/0.13.0/base64/enum.DecodeError.html)
- [url](https://docs.rs/url/2.2.2/url/enum.ParseError.html)
- [time](https://docs.rs/time/0.2.27/time/error/enum.Error.html)

The pattern I'm noticing is that ErrorKind seems to be preferred when you just have a flat enum without any values associated to its variants. A good example of this would be HTTP errors in isahc; they don't need to wrap anything specific i.e. all variants are more or less the same.
When wrapping foreign values that explain the error further (for example, foreign error types), defining the error itself as enum seems to be the way to go. The one exception to this is aho_corasick, which has does this in its ErrorKind enum.

Or, in other words: if your errors all share a bunch of properties and only differ in one (http errors only differ in status code, but all have a potential body, time it took, etc etc), struct + error kind. If your errors variants are fundamentally different from each other, enum.

What's your take?

2021-07-28 13:05 UTC, egfx-notifications commented
I also did a bit of research and come to the same conclusion.

Enum seems to be rather popular for "relabeling" errors under a common library error type while struct + error kind tends to be used if you need some fields containing more information regardless of the error kind, for example if you're building an [error chain](https://docs.rs/error-chain/0.12.4/error_chain/index.html). The separation into Error and ErrorKind also enables displaying them differently, allowing for a rather basic output when displaying ErrorKind and including more contextual information when displaying the Error itself.

Both usages of the struct do not apply here, thus I agree with you that an enum would be suitable for this use case 😃  
We should consider to mark it as [#[non_exhaustive]](https://doc.rust-lang.org/reference/attributes/type_system.html), though, so future additions to the enum won't break code using earlier versions of the library.

2021-07-29 12:29 UTC, theduke requested changes
As mentioned, a struct primarily makes sense if the error always carries some additional payload, like a backtrace.

That's probably overkill here, so an enum is a fine choice. 

Good to merge after the one comment is adressed.

2021-07-29 12:29 UTC, theduke commented on src/lib.rs
> +pub enum FfProbeError {
Let's add `non_exhaustive`. I don't see what additional errors we could have, but it's better to have an option for non-breaking minor releases.

```suggestion
#[non_exhaustive]
pub enum FfProbeError {
```

2021-07-29 13:33 UTC, merged